- name: Install lego
  become: true
  block:

    - name: "Install Let's Encrypt cert service script"
      template:
        src: lets-encrypt-cert.sh
        dest: /usr/local/bin
        owner: root
        group: root
        mode: 0755

    - name: "Install Let's Encrypt cert service template"
      template:
        src: lets-encrypt-cert@.service
        dest: /etc/systemd/system
        owner: root
        group: root
        mode: 0644
      notify: systemd daemon-reload
    
    - name: "Install Let's Encrypt cert service timer template"
      template:
        src: "lets-encrypt-cert@.timer"
        dest: /etc/systemd/system/
        owner: root
        group: root
        mode: 0644
      notify: systemd daemon-reload
