---

- name: "Check if certificates exist or not"
  stat:
    path: "{{ lets_encrypt_directory_path }}/certificates/{{ item.common_name }}.crt"
  with_items: "{{ lets_encrypt_resources }}"
  register: lets_encrypt_resources_stat

- name: "Create certificates"
  shell: "lego \
        --email='{{ lets_encrypt_account_email }}' \
        --csr='{{ lets_encrypt_directory_path }}/requests/{{ item.item.common_name }}.csr' \
        --path='{{ lets_encrypt_directory_path }}' \
        --server='{{ lets_encrypt_server }}' \
        --filename='{{ item.item.common_name }}' \
        {% if item.item.challenge == 'dns' %}--dns='{{ item.item.provider }}'{% endif %} \
        {% if item.item.challenge == 'http' %}--http --http.webroot='{{ item.item.webroot }}'{% endif %} \
        -a
        run"
  with_items: "{{ lets_encrypt_resources_stat.results }}"
  when:
    - item is not skipped
    - item.stat.exists == false
