- name: Install lego
  become: true
  block:

    - name: "Install Let's Encrypt OCSP manager script"
      template:
        src: lets-encrypt-ocsp.sh
        dest: /usr/local/bin
        owner: root
        group: root
        mode: 0755

    - name: "Install Let's Encrypt OCSP manager systemd service template"
      template:
        src: lets-encrypt-ocsp@.service
        dest: /etc/systemd/system
        owner: root
        group: root
        mode: 0644
      notify: systemd daemon-reload

    - name: "Install Let's Encrypt OCSP service timer template"
      template:
        src: "lets-encrypt-ocsp@.timer"
        dest: /etc/systemd/system/
        owner: root
        group: root
        mode: 0644
      notify: systemd daemon-reload
